steps:
  # Start the VM instance
  - name: gcr.io/cloud-builders/gcloud
    args:
      - 'compute'
      - 'instances'
      - 'start'
      - 'project-lras'  # Replace 'project-lras' with your instance name
      - '--zone=us-west4-b'  # Replace 'us-west4-b' with your instance zone
    entrypoint: bash

