steps:
  # Start the VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        gcloud compute instances start project-lras --zone=us-west4-b
