steps:
  # Start the VM  instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        gcloud compute instances start project-lras --zone=us-west4-b

  # Execute the C++ file on the VM instance
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        gcloud compute ssh cloudbuild@project-lras --zone=us-west4-b --command "sudo g++ -o /home/jsutar289/lras /home/jsutar289/lras.cpp && /home/jsutar289/lras"
